/**
 * MCP Seed Data — Realistic mock MCPs for development and demo.
 * Used as fallback when the API is unavailable.
 */

import type { McpDefinition } from "./types";

const now = new Date().toISOString();

export const MOCK_MCPS: McpDefinition[] = [
  {
    id: "datagouv_search",
    name: "Data.gouv Search",
    purpose: "Search French open data portal for datasets and resources",
    description: "Queries the data.gouv.fr API to find public datasets, organizations, and resources. Supports keyword search, filtering by organization, and metadata extraction.",
    effect_type: "search",
    input_contract_ref: "contracts/inputs/SearchQuery.json",
    output_contract_ref: "contracts/outputs/SearchResults.json",
    allowed_agents: ["data_extraction_agent", "evidence_mapping_agent", "research_agent"],
    criticality: "low",
    timeout_seconds: 15,
    retry_policy: "standard",
    cost_profile: "low",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "1.2.0",
    owner: "platform_data_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "insee_sirene_lookup",
    name: "INSEE SIRENE Lookup",
    purpose: "Look up French company information from the SIRENE registry",
    description: "Retrieves official company data from INSEE SIRENE database: SIREN/SIRET numbers, legal form, NAF code, address, workforce category, creation date.",
    effect_type: "read",
    input_contract_ref: "contracts/inputs/CompanyLookup.json",
    output_contract_ref: "contracts/outputs/CompanyInfo.json",
    allowed_agents: ["data_extraction_agent", "consistency_review_agent", "compliance_agent"],
    criticality: "medium",
    timeout_seconds: 10,
    retry_policy: "standard",
    cost_profile: "low",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "2.0.1",
    owner: "platform_data_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "service_public_company",
    name: "Service-Public Company Lookup",
    purpose: "Retrieve public administration records for French companies",
    description: "Accesses service-public.fr APIs to retrieve administrative obligations, regulatory status, and compliance requirements for French legal entities.",
    effect_type: "read",
    input_contract_ref: "contracts/inputs/CompanyLookup.json",
    output_contract_ref: "contracts/outputs/AdminRecords.json",
    allowed_agents: ["compliance_agent", "regulatory_agent", "evidence_mapping_agent"],
    criticality: "medium",
    timeout_seconds: 20,
    retry_policy: "retry_twice",
    cost_profile: "low",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "1.0.0",
    owner: "platform_compliance_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "bodacc_events",
    name: "BODACC Events Adapter",
    purpose: "Monitor and retrieve French legal business events from BODACC",
    description: "Searches the Bulletin Officiel des Annonces Civiles et Commerciales for company events: creation, modification, dissolution, collective proceedings, sales.",
    effect_type: "search",
    input_contract_ref: "contracts/inputs/EventSearch.json",
    output_contract_ref: "contracts/outputs/LegalEvents.json",
    allowed_agents: ["risk_analysis_agent", "consistency_review_agent", "compliance_agent"],
    criticality: "high",
    timeout_seconds: 15,
    retry_policy: "standard",
    cost_profile: "medium",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "1.1.0",
    owner: "platform_risk_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "boamp_search",
    name: "BOAMP Search Adapter",
    purpose: "Search French public procurement announcements",
    description: "Queries the Bulletin Officiel des Annonces des Marchés Publics to find public tenders, contract awards, and procurement opportunities.",
    effect_type: "search",
    input_contract_ref: "contracts/inputs/TenderSearch.json",
    output_contract_ref: "contracts/outputs/TenderResults.json",
    allowed_agents: ["research_agent", "data_extraction_agent"],
    criticality: "low",
    timeout_seconds: 15,
    retry_policy: "standard",
    cost_profile: "low",
    approval_required: false,
    audit_required: false,
    status: "active",
    version: "1.0.0",
    owner: "platform_data_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "web_search",
    name: "Web Search",
    purpose: "General web search for information gathering",
    description: "Performs web searches using configurable search engines. Returns structured results with titles, URLs, snippets, and relevance scores.",
    effect_type: "search",
    input_contract_ref: "contracts/inputs/WebSearch.json",
    output_contract_ref: "contracts/outputs/WebResults.json",
    allowed_agents: ["research_agent", "evidence_mapping_agent", "data_extraction_agent"],
    criticality: "low",
    timeout_seconds: 10,
    retry_policy: "retry_once",
    cost_profile: "low",
    approval_required: false,
    audit_required: false,
    status: "active",
    version: "2.1.0",
    owner: "platform_infra_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "document_parser",
    name: "Document Parser",
    purpose: "Parse uploaded documents and extract machine-readable content",
    description: "Reads PDF, DOCX, XLSX, and image files. Extracts text, tables, metadata, and structural markers. Supports OCR for scanned documents.",
    effect_type: "read",
    input_contract_ref: "contracts/inputs/DocumentParserInput.json",
    output_contract_ref: "contracts/outputs/DocumentParserOutput.json",
    allowed_agents: ["data_extraction_agent", "consistency_review_agent", "evidence_mapping_agent"],
    criticality: "high",
    timeout_seconds: 60,
    retry_policy: "retry_twice",
    cost_profile: "medium",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "3.0.0",
    owner: "platform_ai_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "consistency_checker",
    name: "Consistency Checker",
    purpose: "Detect contradictions and anomalies across multiple data sources",
    description: "Compares extracted fields across documents and data sources. Identifies contradictions, mismatches, suspicious gaps, and temporal inconsistencies.",
    effect_type: "compute",
    input_contract_ref: "contracts/inputs/ConsistencyInput.json",
    output_contract_ref: "contracts/outputs/ConsistencyResult.json",
    allowed_agents: ["consistency_review_agent", "risk_analysis_agent"],
    criticality: "high",
    timeout_seconds: 30,
    retry_policy: "standard",
    cost_profile: "medium",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "1.5.0",
    owner: "platform_ai_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "external_report_generator",
    name: "External Report Generator",
    purpose: "Generate formatted reports for external stakeholders",
    description: "Creates PDF/DOCX reports from structured data. Applies templates, formatting rules, and compliance checks before output.",
    effect_type: "write",
    input_contract_ref: "contracts/inputs/ReportRequest.json",
    output_contract_ref: "contracts/outputs/ReportOutput.json",
    allowed_agents: ["report_agent", "synthesis_agent"],
    criticality: "high",
    timeout_seconds: 45,
    retry_policy: "standard",
    cost_profile: "high",
    approval_required: true,
    audit_required: true,
    status: "active",
    version: "1.0.0",
    owner: "platform_ops_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "email_sender",
    name: "Email Sender",
    purpose: "Send emails to external recipients on behalf of the platform",
    description: "Sends transactional and notification emails. Requires approval for external-facing communications. Supports templates and attachments.",
    effect_type: "act",
    input_contract_ref: null,
    output_contract_ref: null,
    allowed_agents: ["notification_agent"],
    criticality: "high",
    timeout_seconds: 15,
    retry_policy: "retry_once",
    cost_profile: "low",
    approval_required: true,
    audit_required: true,
    status: "disabled",
    version: "0.9.0",
    owner: "platform_ops_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "scoring_engine",
    name: "Scoring Engine",
    purpose: "Compute risk and quality scores based on structured data",
    description: "Applies configurable scoring models to compute credit risk, completeness, consistency, and overall quality scores.",
    effect_type: "compute",
    input_contract_ref: null,
    output_contract_ref: null,
    allowed_agents: ["risk_analysis_agent", "policy_decision_agent", "synthesis_agent"],
    criticality: "medium",
    timeout_seconds: 10,
    retry_policy: "standard",
    cost_profile: "low",
    approval_required: false,
    audit_required: true,
    status: "active",
    version: "2.0.0",
    owner: "platform_ai_team",
    created_at: now,
    updated_at: now,
  },
  {
    id: "knowledge_store",
    name: "Knowledge Store",
    purpose: "Store and retrieve knowledge entries for long-term agent memory",
    description: "Provides vector-based semantic search over the platform knowledge base. Supports embedding, retrieval, and contextual ranking.",
    effect_type: "search",
    input_contract_ref: null,
    output_contract_ref: null,
    allowed_agents: ["research_agent", "evidence_mapping_agent", "data_extraction_agent", "synthesis_agent"],
    criticality: "medium",
    timeout_seconds: 5,
    retry_policy: "standard",
    cost_profile: "low",
    approval_required: false,
    audit_required: false,
    status: "active",
    version: "1.3.0",
    owner: "platform_ai_team",
    created_at: now,
    updated_at: now,
  },
];
