;(function(){
/* Orkestra — mock data built from real frontend/src schemas */

const FAMILIES = [
  { id: "retrieval", label: "Retrieval", description: "Sources, search, parsing" },
  { id: "reasoning", label: "Reasoning", description: "Planning, decomposition, synthesis" },
  { id: "writing", label: "Writing", description: "Drafting and formatting outputs" },
  { id: "orchestration", label: "Orchestration", description: "Pipelines of agents" },
  { id: "validation", label: "Validation", description: "Contract + behavior checks" },
  { id: "integration", label: "Integration", description: "External systems via MCPs" },
];

const MCP_CATALOG = [
  { id: "mcp_http_fetch",      name: "HTTP Fetch",        purpose: "Fetch arbitrary HTTP resources",        effect_type: "read_external",  criticality: "medium",   approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_postgres_ro",     name: "Postgres (RO)",     purpose: "Read-only SQL over internal Postgres",  effect_type: "read_internal",  criticality: "medium",   approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_postgres_rw",     name: "Postgres (RW)",     purpose: "Write SQL — gated by approval",         effect_type: "write_internal", criticality: "critical", approval_required: true,  obot_state: "published", orkestra_state: "restricted" },
  { id: "mcp_vector_pgv",      name: "pgvector Search",   purpose: "Semantic search over embeddings",       effect_type: "read_internal",  criticality: "low",      approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_slack_send",      name: "Slack Send",        purpose: "Post messages to Slack",                effect_type: "write_external", criticality: "high",     approval_required: true,  obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_github_rw",       name: "GitHub (RW)",       purpose: "Read/write issues, PRs, comments",      effect_type: "write_external", criticality: "high",     approval_required: true,  obot_state: "published", orkestra_state: "restricted" },
  { id: "mcp_web_search",      name: "Web Search",        purpose: "Public web search (Brave)",             effect_type: "read_external",  criticality: "low",      approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_fs_ro",           name: "Filesystem (RO)",   purpose: "Read-only workspace files",             effect_type: "read_internal",  criticality: "low",      approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_sandbox_python",  name: "Python Sandbox",    purpose: "Ephemeral code execution",              effect_type: "compute",        criticality: "medium",   approval_required: false, obot_state: "published", orkestra_state: "active"     },
  { id: "mcp_jira",            name: "Jira",              purpose: "Issue tracker integration",             effect_type: "write_external", criticality: "high",     approval_required: true,  obot_state: "degraded",  orkestra_state: "warning"    },
];

const SKILLS = [
  { skill_id: "skl_semantic_search",  label: "Semantic search",      category: "retrieval" },
  { skill_id: "skl_sql_query",        label: "SQL query authoring",  category: "retrieval" },
  { skill_id: "skl_url_scrape",       label: "URL scrape + parse",   category: "retrieval" },
  { skill_id: "skl_plan_decompose",   label: "Plan decomposition",   category: "reasoning" },
  { skill_id: "skl_summarize_long",   label: "Long-context summary", category: "reasoning" },
  { skill_id: "skl_self_critique",    label: "Self-critique",        category: "reasoning" },
  { skill_id: "skl_markdown_compose", label: "Markdown compose",     category: "writing" },
  { skill_id: "skl_schema_fill",      label: "Schema-constrained fill", category: "writing" },
  { skill_id: "skl_contract_check",   label: "Contract validation",  category: "validation" },
  { skill_id: "skl_judge_rubric",     label: "Rubric-based judging", category: "validation" },
  { skill_id: "skl_route_delegate",   label: "Route & delegate",     category: "orchestration" },
];

function skillsResolved(ids) {
  return (ids || []).map(id => SKILLS.find(s => s.skill_id === id)).filter(Boolean);
}

// Seven specimens spanning every lifecycle state
const AGENTS = [
  {
    id: "agent_retriever_docs",
    name: "retriever-docs",
    family_id: "retrieval",
    purpose: "Fetch and distill the most relevant passages from the internal docs corpus for a given query, returning a structured evidence bundle.",
    description: "Primary retrieval worker used by the Answer orchestrator. Reads pgvector + filesystem, never writes.",
    skill_ids: ["skl_semantic_search", "skl_url_scrape", "skl_summarize_long"],
    selection_hints: { "prefer_when": ["internal_docs", "policy_lookup"], "avoid_when": ["external_research"], "latency_target_ms": 2500 },
    allowed_mcps: ["mcp_vector_pgv", "mcp_fs_ro", "mcp_postgres_ro"],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  "contracts://retrieval/query.v2",
    output_contract_ref: "contracts://retrieval/evidence_bundle.v2",
    criticality: "high",
    cost_profile: "low",
    limitations: ["no multilingual corpus yet", "max 12 docs per call"],
    prompt_ref: "prompts://retriever-docs@2.3.0",
    prompt_content: `You are retriever-docs, a read-only retrieval agent.

Given <query>, return an evidence_bundle with:
  - items[]: { doc_id, span, score, excerpt }
  - coverage: low|medium|high
  - gaps: string[]

Rules:
  1. Never fabricate — only cite retrieved passages.
  2. Prefer high-score, diverse sources. Deduplicate by doc_id+span.
  3. If coverage < medium, populate gaps and set resolved=false.
  4. Budget: at most 12 items, 400 tokens per excerpt.`,
    skills_ref: "skills://retriever-docs@2.3.0",
    skills_content: `# retriever-docs skills\n\n- semantic_search over pgvector (collections: docs_primary, docs_archive)\n- url_scrape over approved domains only\n- long-context summarization up to 120k tokens`,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "2.3.0",
    status: "active",
    owner: "ada.park",
    last_test_status: "passed",
    last_validated_at: "2026-04-17T09:12:04Z",
    usage_count: 18342,
    created_at: "2025-11-02T14:30:00Z",
    updated_at: "2026-04-17T09:12:04Z",
  },
  {
    id: "agent_router_primary",
    name: "router-primary",
    family_id: "orchestration",
    purpose: "Dispatch a user request to the correct downstream agent pipeline based on intent classification and routing rules.",
    description: "Sequential orchestrator. Hands off to retrieval → reasoning → writer in order, but can be switched to dynamic routing.",
    skill_ids: ["skl_route_delegate", "skl_plan_decompose"],
    selection_hints: { "routing_style": "sequential", "allow_skip": true },
    allowed_mcps: [],
    forbidden_effects: ["write_external"],
    input_contract_ref:  "contracts://orchestration/request.v1",
    output_contract_ref: "contracts://orchestration/plan.v1",
    criticality: "critical",
    cost_profile: "medium",
    limitations: [],
    prompt_ref: "prompts://router-primary@1.4.0",
    prompt_content: `You are router-primary, the top-level orchestrator.\n\nInspect <request.intent> and dispatch to the ordered pipeline below, passing the result of each step forward. If an agent returns resolved=false you MAY re-plan within dynamic mode; in sequential mode, fail fast.`,
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: ["agent_retriever_docs", "agent_planner_main", "agent_writer_markdown"],
    routing_mode: "sequential",
    version: "1.4.0",
    status: "active",
    owner: "ada.park",
    last_test_status: "passed",
    last_validated_at: "2026-04-16T18:02:00Z",
    usage_count: 24115,
    created_at: "2025-10-14T12:00:00Z",
    updated_at: "2026-04-16T18:02:00Z",
  },
  {
    id: "agent_planner_main",
    name: "planner-main",
    family_id: "reasoning",
    purpose: "Decompose a retrieved evidence bundle into an ordered, schema-constrained plan of sub-tasks for downstream writers.",
    description: "Reads only. Produces plan.v1 objects consumed by writer-markdown.",
    skill_ids: ["skl_plan_decompose", "skl_self_critique", "skl_schema_fill"],
    selection_hints: { "needs_evidence": true, "max_steps": 8 },
    allowed_mcps: ["mcp_vector_pgv"],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  "contracts://retrieval/evidence_bundle.v2",
    output_contract_ref: "contracts://reasoning/plan.v1",
    criticality: "high",
    cost_profile: "medium",
    limitations: ["single language"],
    prompt_ref: "prompts://planner-main@1.2.1",
    prompt_content: `You are planner-main.\n\nConsume evidence_bundle. Return plan.v1 with:\n  - steps: ordered array (max 8), each { id, kind, inputs_ref, output_schema }\n  - rationale: short string per step\n\nSelf-critique pass: if any step lacks evidence, mark it speculative=true.`,
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "1.2.1",
    status: "registered",
    owner: "theo.nguyen",
    last_test_status: "passed",
    last_validated_at: "2026-04-15T10:40:11Z",
    usage_count: 8421,
    created_at: "2025-12-09T10:00:00Z",
    updated_at: "2026-04-15T10:40:11Z",
  },
  {
    id: "agent_writer_markdown",
    name: "writer-markdown",
    family_id: "writing",
    purpose: "Turn a validated plan plus evidence bundle into a clean Markdown answer with citations, tables, and code blocks.",
    description: null,
    skill_ids: ["skl_markdown_compose", "skl_schema_fill"],
    selection_hints: { "output_style": "markdown_with_citations" },
    allowed_mcps: [],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  "contracts://reasoning/plan.v1",
    output_contract_ref: "contracts://writing/answer.v3",
    criticality: "medium",
    cost_profile: "low",
    limitations: ["no LaTeX rendering yet"],
    prompt_ref: "prompts://writer-markdown@3.1.0",
    prompt_content: `You are writer-markdown.\n\nCompose a final answer from <plan> + <evidence>. Always include a citations section linking back to evidence_bundle.items[].doc_id. Do not invent sources.`,
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-haiku-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "3.1.0",
    status: "tested",
    owner: "liam.rosa",
    last_test_status: "passed_with_warnings",
    last_validated_at: "2026-04-14T08:22:00Z",
    usage_count: 15220,
    created_at: "2025-09-20T09:00:00Z",
    updated_at: "2026-04-14T08:22:00Z",
  },
  {
    id: "agent_sql_writer",
    name: "sql-writer",
    family_id: "integration",
    purpose: "Generate and execute parameterized SQL write statements against Postgres under a mandatory approval gate.",
    description: "Critical agent — requires human approval before any write. Uses mcp_postgres_rw only within SECURITY REVIEW scope.",
    skill_ids: ["skl_sql_query", "skl_schema_fill", "skl_contract_check"],
    selection_hints: { "requires_approval": true, "approval_ttl_s": 900 },
    allowed_mcps: ["mcp_postgres_rw", "mcp_postgres_ro"],
    forbidden_effects: ["write_external"],
    input_contract_ref:  "contracts://integration/sql_write_request.v1",
    output_contract_ref: "contracts://integration/sql_write_result.v1",
    criticality: "critical",
    cost_profile: "low",
    limitations: ["no DDL", "single-transaction only", "max 10k rows affected"],
    prompt_ref: "prompts://sql-writer@0.4.2",
    prompt_content: `DRAFT — not production.\n\nYou are sql-writer. Generate a SINGLE parameterized SQL statement matching the request. Never concatenate user input. Always preview the affected row count and wait for approved=true before execution.`,
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "0.4.2",
    status: "designed",
    owner: "maya.kumar",
    last_test_status: "not_tested",
    last_validated_at: null,
    usage_count: 0,
    created_at: "2026-03-10T14:30:00Z",
    updated_at: "2026-04-12T11:05:00Z",
  },
  {
    id: "agent_validator_contracts",
    name: "validator-contracts",
    family_id: "validation",
    purpose: "Validate that an agent's output matches its declared output_contract_ref, emitting per-field diagnostics.",
    description: "Used by Test Lab judges and at runtime behind a feature flag.",
    skill_ids: ["skl_contract_check", "skl_judge_rubric"],
    selection_hints: { "runs_in": ["test_lab", "runtime_audit"] },
    allowed_mcps: [],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  null,
    output_contract_ref: "contracts://validation/diagnostics.v1",
    criticality: "medium",
    cost_profile: "low",
    limitations: [],
    prompt_ref: "prompts://validator-contracts@0.9.0",
    prompt_content: "You are validator-contracts. Given <candidate_output> and <output_contract>, report per-field pass/fail with rationale.",
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-haiku-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "0.9.0",
    status: "draft",
    owner: "noor.ali",
    last_test_status: "not_tested",
    last_validated_at: null,
    usage_count: 0,
    created_at: "2026-04-10T16:20:00Z",
    updated_at: "2026-04-18T10:11:00Z",
  },
  {
    id: "agent_web_scout_v1",
    name: "web-scout-v1",
    family_id: "retrieval",
    purpose: "Search the public web and summarize top results for a free-form question.",
    description: "Superseded by web-scout-v2 — retained for read-only historical runs.",
    skill_ids: ["skl_semantic_search", "skl_url_scrape", "skl_summarize_long"],
    selection_hints: { "freshness_days": 30 },
    allowed_mcps: ["mcp_web_search", "mcp_http_fetch"],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref: "contracts://retrieval/query.v1",
    output_contract_ref: "contracts://retrieval/evidence_bundle.v1",
    criticality: "medium",
    cost_profile: "medium",
    limitations: ["v1 contract — do not use in new pipelines"],
    prompt_ref: "prompts://web-scout@1.0.0",
    prompt_content: "(legacy prompt — superseded by web-scout-v2)",
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-haiku-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "1.0.0",
    status: "deprecated",
    owner: "ada.park",
    last_test_status: "passed",
    last_validated_at: "2025-12-01T00:00:00Z",
    usage_count: 44200,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2026-03-02T10:00:00Z",
  },
  {
    id: "agent_judge_rubric",
    name: "judge-rubric",
    family_id: "validation",
    purpose: "Score an agent's response against a human-authored rubric and emit a pass/fail with justification.",
    description: "Read-only judge used by Test Lab. Deterministic temperature.",
    skill_ids: ["skl_judge_rubric", "skl_self_critique"],
    selection_hints: { "use_in": ["test_lab"], "temperature": 0 },
    allowed_mcps: [],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  "contracts://validation/judge_request.v1",
    output_contract_ref: "contracts://validation/judge_verdict.v1",
    criticality: "medium",
    cost_profile: "low",
    limitations: [],
    prompt_ref: "prompts://judge-rubric@1.1.0",
    prompt_content: "You are judge-rubric. Given <rubric> and <candidate>, emit {verdict: pass|fail|partial, scores: {criterion: 0..1}, rationale}.",
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "1.1.0",
    status: "active",
    owner: "noor.ali",
    last_test_status: "passed",
    last_validated_at: "2026-04-10T12:00:00Z",
    usage_count: 6102,
    created_at: "2025-12-15T00:00:00Z",
    updated_at: "2026-04-10T12:00:00Z",
  },
  {
    id: "agent_approval_gate_legacy",
    name: "approval-gate-legacy",
    family_id: "orchestration",
    purpose: "Legacy human-in-the-loop approval shim. Replaced by the native Approvals surface.",
    description: null,
    skill_ids: ["skl_route_delegate"],
    selection_hints: {},
    allowed_mcps: ["mcp_slack_send"],
    forbidden_effects: ["write_internal"],
    input_contract_ref:  "contracts://orchestration/approval_request.v0",
    output_contract_ref: "contracts://orchestration/approval_response.v0",
    criticality: "high",
    cost_profile: "low",
    limitations: [],
    prompt_ref: null,
    prompt_content: "(disabled)",
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-haiku-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "0.7.0",
    status: "disabled",
    owner: "ada.park",
    last_test_status: "failed",
    last_validated_at: "2026-02-01T00:00:00Z",
    usage_count: 0,
    created_at: "2025-07-01T00:00:00Z",
    updated_at: "2026-03-12T14:00:00Z",
  },
  {
    id: "agent_research_beta",
    name: "research-beta",
    family_id: "reasoning",
    purpose: "Experimental deep-research agent. Archived — kept for provenance.",
    description: null,
    skill_ids: ["skl_plan_decompose", "skl_summarize_long"],
    selection_hints: {},
    allowed_mcps: ["mcp_web_search"],
    forbidden_effects: ["write_internal", "write_external"],
    input_contract_ref:  null,
    output_contract_ref: null,
    criticality: "low",
    cost_profile: "high",
    limitations: ["archived"],
    prompt_ref: null,
    prompt_content: "(archived)",
    skills_ref: null,
    skills_content: null,
    soul_content: null,
    llm_provider: "anthropic",
    llm_model: "claude-sonnet-4.5",
    allow_code_execution: false,
    allowed_builtin_tools: [],
    pipeline_agent_ids: [],
    routing_mode: null,
    version: "0.2.0",
    status: "archived",
    owner: "theo.nguyen",
    last_test_status: "not_tested",
    last_validated_at: null,
    usage_count: 0,
    created_at: "2025-05-01T00:00:00Z",
    updated_at: "2025-11-30T00:00:00Z",
  },
];

// Fill skills_resolved
for (const a of AGENTS) a.skills_resolved = skillsResolved(a.skill_ids);

// Gate definitions mirror lib/agent-lifecycle/helpers.ts
const MAIN_PATH = ["draft", "designed", "tested", "registered", "active"];
const MAIN_LABELS = { draft: "Draft", designed: "Designed", tested: "Tested", registered: "Registered", active: "Active" };
const GATES = [
  { from: "draft",      to: "designed",   title: "Definition complete",  description: "Agent definition, prompt, and skills must be fully specified." },
  { from: "designed",   to: "tested",     title: "Qualification passed", description: "Behavioral test pack must be executed and all checks passed." },
  { from: "tested",     to: "registered", title: "Registry validated",   description: "Agent contracts and configuration validated for registry inclusion." },
  { from: "registered", to: "active",     title: "Activation approved",  description: "Final approval for production activation." },
];

// Chat transcripts
const SAMPLE_CHAT = [
  { role: "user", content: "Can you pull the most recent evidence we have on the onboarding drop-off between step 2 and 3?" },
  {
    role: "agent",
    content: '{"resolved": true, "items_count": 7, "coverage": "high", "gaps": []}',
    tool_calls: [
      { tool_name: "semantic_search",       tool_output: '{"hits": 7, "ms": 184}' },
      { tool_name: "fs_ro::read_file",      tool_output: '"/docs/metrics/onboarding_week_16.md"' },
    ],
    duration_ms: 1842,
  },
  { role: "user", content: "Great — any gaps worth flagging?" },
  { role: "agent", content: "Coverage is high but all sources pre-date the April 10 funnel redesign. Rerun next week once fresh data lands.", tool_calls: [], duration_ms: 612 },
];

window.OrkestraData = {
  FAMILIES, MCP_CATALOG, SKILLS, AGENTS,
  MAIN_PATH, MAIN_LABELS, GATES,
  SAMPLE_CHAT,
};

})();