"""Seed script — populate the MCP registry with realistic sample data."""

import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database import get_async_session_factory, Base, get_engine
from app.models.registry import MCPDefinition
from app.models.enums import MCPStatus


SEED_MCPS = [
    {
        "id": "datagouv_search",
        "name": "Data.gouv Search",
        "purpose": "Search French open data portal for datasets and resources",
        "description": "Queries the data.gouv.fr API to find public datasets, organizations, and resources. Supports keyword search, filtering by organization, and metadata extraction.",
        "effect_type": "search",
        "criticality": "low",
        "timeout_seconds": 15,
        "retry_policy": "standard",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["data_extraction_agent", "evidence_mapping_agent", "research_agent"],
        "input_contract_ref": "contracts/inputs/SearchQuery.json",
        "output_contract_ref": "contracts/outputs/SearchResults.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.2.0",
        "owner": "platform_data_team",
    },
    {
        "id": "insee_sirene_lookup",
        "name": "INSEE SIRENE Lookup",
        "purpose": "Look up French company information from the SIRENE registry",
        "description": "Retrieves official company data from INSEE SIRENE database: SIREN/SIRET numbers, legal form, NAF code, address, workforce category, creation date.",
        "effect_type": "read",
        "criticality": "medium",
        "timeout_seconds": 10,
        "retry_policy": "standard",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["data_extraction_agent", "consistency_review_agent", "compliance_agent"],
        "input_contract_ref": "contracts/inputs/CompanyLookup.json",
        "output_contract_ref": "contracts/outputs/CompanyInfo.json",
        "status": MCPStatus.ACTIVE,
        "version": "2.0.1",
        "owner": "platform_data_team",
    },
    {
        "id": "service_public_company",
        "name": "Service-Public Company Lookup",
        "purpose": "Retrieve public administration records for French companies",
        "description": "Accesses service-public.fr APIs to retrieve administrative obligations, regulatory status, and compliance requirements for French legal entities.",
        "effect_type": "read",
        "criticality": "medium",
        "timeout_seconds": 20,
        "retry_policy": "retry_twice",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["compliance_agent", "regulatory_agent", "evidence_mapping_agent"],
        "input_contract_ref": "contracts/inputs/CompanyLookup.json",
        "output_contract_ref": "contracts/outputs/AdminRecords.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.0.0",
        "owner": "platform_compliance_team",
    },
    {
        "id": "bodacc_events",
        "name": "BODACC Events Adapter",
        "purpose": "Monitor and retrieve French legal business events from BODACC",
        "description": "Searches the Bulletin Officiel des Annonces Civiles et Commerciales for company events: creation, modification, dissolution, collective proceedings, sales.",
        "effect_type": "search",
        "criticality": "high",
        "timeout_seconds": 15,
        "retry_policy": "standard",
        "cost_profile": "medium",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["risk_analysis_agent", "consistency_review_agent", "compliance_agent"],
        "input_contract_ref": "contracts/inputs/EventSearch.json",
        "output_contract_ref": "contracts/outputs/LegalEvents.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.1.0",
        "owner": "platform_risk_team",
    },
    {
        "id": "boamp_search",
        "name": "BOAMP Search Adapter",
        "purpose": "Search French public procurement announcements",
        "description": "Queries the Bulletin Officiel des Annonces des Marches Publics to find public tenders, contract awards, and procurement opportunities.",
        "effect_type": "search",
        "criticality": "low",
        "timeout_seconds": 15,
        "retry_policy": "standard",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": False,
        "allowed_agents": ["research_agent", "data_extraction_agent"],
        "input_contract_ref": "contracts/inputs/TenderSearch.json",
        "output_contract_ref": "contracts/outputs/TenderResults.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.0.0",
        "owner": "platform_data_team",
    },
    {
        "id": "web_search",
        "name": "Web Search",
        "purpose": "General web search for information gathering",
        "description": "Performs web searches using configurable search engines. Returns structured results with titles, URLs, snippets, and relevance scores.",
        "effect_type": "search",
        "criticality": "low",
        "timeout_seconds": 10,
        "retry_policy": "retry_once",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": False,
        "allowed_agents": ["research_agent", "evidence_mapping_agent", "data_extraction_agent"],
        "input_contract_ref": "contracts/inputs/WebSearch.json",
        "output_contract_ref": "contracts/outputs/WebResults.json",
        "status": MCPStatus.ACTIVE,
        "version": "2.1.0",
        "owner": "platform_infra_team",
    },
    {
        "id": "document_parser",
        "name": "Document Parser",
        "purpose": "Parse uploaded documents and extract machine-readable content",
        "description": "Reads PDF, DOCX, XLSX, and image files. Extracts text, tables, metadata, and structural markers. Supports OCR for scanned documents.",
        "effect_type": "read",
        "criticality": "high",
        "timeout_seconds": 60,
        "retry_policy": "retry_twice",
        "cost_profile": "medium",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["data_extraction_agent", "consistency_review_agent", "evidence_mapping_agent"],
        "input_contract_ref": "contracts/inputs/DocumentParserInput.json",
        "output_contract_ref": "contracts/outputs/DocumentParserOutput.json",
        "status": MCPStatus.ACTIVE,
        "version": "3.0.0",
        "owner": "platform_ai_team",
    },
    {
        "id": "consistency_checker",
        "name": "Consistency Checker",
        "purpose": "Detect contradictions and anomalies across multiple data sources",
        "description": "Compares extracted fields across documents and data sources. Identifies contradictions, mismatches, suspicious gaps, and temporal inconsistencies.",
        "effect_type": "compute",
        "criticality": "high",
        "timeout_seconds": 30,
        "retry_policy": "standard",
        "cost_profile": "medium",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["consistency_review_agent", "risk_analysis_agent"],
        "input_contract_ref": "contracts/inputs/ConsistencyInput.json",
        "output_contract_ref": "contracts/outputs/ConsistencyResult.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.5.0",
        "owner": "platform_ai_team",
    },
    {
        "id": "external_report_generator",
        "name": "External Report Generator",
        "purpose": "Generate formatted reports for external stakeholders",
        "description": "Creates PDF/DOCX reports from structured data. Applies templates, formatting rules, and compliance checks before output.",
        "effect_type": "write",
        "criticality": "high",
        "timeout_seconds": 45,
        "retry_policy": "standard",
        "cost_profile": "high",
        "approval_required": True,
        "audit_required": True,
        "allowed_agents": ["report_agent", "synthesis_agent"],
        "input_contract_ref": "contracts/inputs/ReportRequest.json",
        "output_contract_ref": "contracts/outputs/ReportOutput.json",
        "status": MCPStatus.ACTIVE,
        "version": "1.0.0",
        "owner": "platform_ops_team",
    },
    {
        "id": "email_sender",
        "name": "Email Sender",
        "purpose": "Send emails to external recipients on behalf of the platform",
        "description": "Sends transactional and notification emails. Requires approval for external-facing communications. Supports templates and attachments.",
        "effect_type": "act",
        "criticality": "high",
        "timeout_seconds": 15,
        "retry_policy": "retry_once",
        "cost_profile": "low",
        "approval_required": True,
        "audit_required": True,
        "allowed_agents": ["notification_agent"],
        "status": MCPStatus.DISABLED,
        "version": "0.9.0",
        "owner": "platform_ops_team",
    },
    {
        "id": "scoring_engine",
        "name": "Scoring Engine",
        "purpose": "Compute risk and quality scores based on structured data",
        "description": "Applies configurable scoring models to compute credit risk, completeness, consistency, and overall quality scores.",
        "effect_type": "compute",
        "criticality": "medium",
        "timeout_seconds": 10,
        "retry_policy": "standard",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": True,
        "allowed_agents": ["risk_analysis_agent", "policy_decision_agent", "synthesis_agent"],
        "status": MCPStatus.ACTIVE,
        "version": "2.0.0",
        "owner": "platform_ai_team",
    },
    {
        "id": "knowledge_store",
        "name": "Knowledge Store",
        "purpose": "Store and retrieve knowledge entries for long-term agent memory",
        "description": "Provides vector-based semantic search over the platform knowledge base. Supports embedding, retrieval, and contextual ranking.",
        "effect_type": "search",
        "criticality": "medium",
        "timeout_seconds": 5,
        "retry_policy": "standard",
        "cost_profile": "low",
        "approval_required": False,
        "audit_required": False,
        "allowed_agents": ["research_agent", "evidence_mapping_agent", "data_extraction_agent", "synthesis_agent"],
        "status": MCPStatus.ACTIVE,
        "version": "1.3.0",
        "owner": "platform_ai_team",
    },
]


async def seed():
    engine = get_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    factory = get_async_session_factory()
    async with factory() as session:
        for mcp_data in SEED_MCPS:
            existing = await session.get(MCPDefinition, mcp_data["id"])
            if existing:
                print(f"  Skip {mcp_data['id']} (already exists)")
                continue
            mcp = MCPDefinition(**mcp_data)
            session.add(mcp)
            print(f"  Added {mcp_data['id']}")
        await session.commit()
    print(f"\nSeeded {len(SEED_MCPS)} MCPs")


if __name__ == "__main__":
    asyncio.run(seed())
